behaviors:
  Main1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.0005
      beta: 0.002
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.1
        gamma: 0.99
        demo_path: "ImitationDemos/MultipleSensors.demo"
      curiosity:
        strength: 0.003
        gamma: 0.98
        network_settings:
          hidden_units: 256
        learning_rate: 1.0e-5
    behavioral_cloning:
        strength: 0.3
        demo_path: "ImitationDemos/MultipleSensors.demo"
        steps: 500000
    max_steps: 20000000
    time_horizon: 1024
    summary_freq: 25000
environment_parameters:
  maze1:
    curriculum:
      - name: "Lesson 0" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 900
        value: 0
      - name: "Lesson 1" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 1
      - name: "Lesson 2"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 2
      - name: "Lesson 3"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 800
        value: 3
      - name: "Lesson 4"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 800
        value: 4
      - name: "Lesson 5"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 250
          threshold: 800
        value: 5