behaviors:
  CurriculumAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
        learning_rate: 1.0e-5
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 5000
environment_parameters:
  navigation:
    curriculum:
      # - name: "Lesson 1: Open" # This is the start of the second lesson
      #   completion_criteria:
      #     measure: reward
      #     behavior: CurriculumAgent
      #     signal_smoothing: true
      #     min_lesson_length: 1000
      #     threshold: 9
      #   value: 0
      # - name: "Lesson 2: Open with Obstacles"
      #   completion_criteria:
      #     measure: reward
      #     behavior: CurriculumAgent
      #     signal_smoothing: true
      #     min_lesson_length: 30
      #     threshold: 5
      #   value: 1
      - name: "Lesson 3: Closed Corridors"
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 7.5
        value: 2
      - name: "Lesson 4: Closed Corners"
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 7.5
        value: 3
      - name: "Lesson 5: Closed Corridors Complex"
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 7.5
        value: 4