behaviors:
  Main1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 0.0005
      beta: 0.003
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      gail:
        strength: 0.1
        gamma: 0.99
        demo_path: "ImitationDemos/MultipleSensors_2.demo"
      curiosity:
        strength: 0.005
        gamma: 0.985
        network_settings:
          hidden_units: 256
          normalize: true
        learning_rate: 1.0e-5
    behavioral_cloning:
        strength: 0.5
        demo_path: "ImitationDemos/MultipleSensors_2.demo"
        steps: 2000000
    max_steps: 25000000
    time_horizon: 1024
    summary_freq: 50000
environment_parameters:
  maze1:
    curriculum:
      - name: "Lesson 0" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 0
      - name: "Lesson 1" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 800
        value: 1
      - name: "Lesson 2"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 800
        value: 2
      - name: "Lesson 3"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 800
        value: 3
      - name: "Lesson 4"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 800
        value: 4
      - name: "Lesson 5"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 800
        value: 5
      - name: "Lesson 6"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 800
        value: 6
      - name: "Lesson 7"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 800
        value: 7