behaviors:
  CurriculumAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: "ImitationDemos/Maze3.demo"
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
        learning_rate: 1.0e-5
    behavioral_cloning:
        strength: 0.5
        demo_path: "ImitationDemos/Maze3.demo"
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 5000
environment_parameters:
  maze1:
    curriculum:
      - name: "Lesson 1" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 9
        value: 0
      - name: "Lesson 2"
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 7
        value: 1
      - name: "Lesson 3"
        completion_criteria:
          measure: reward
          behavior: CurriculumAgent
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 7.5
        value: 2