behaviors:
  Main1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 200
      buffer_size: 2000
      learning_rate: 0.0002
      beta: 0.0002
      epsilon: 0.2
      lambd: 0.995
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      memory:
        sequence_length: 64
        memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.975
        strength: 0.99
      # gail:
      #   strength: 0.15
      #   gamma: 0.95
      #   learning_rate: 0.00075
      #   demo_path: "ImitationDemos/MultiSensor_Discrete2"
      curiosity:
        strength: 0.001
        gamma: 0.95
        network_settings:
          hidden_units: 256
          normalize: false
        learning_rate: 0.00075
    # behavioral_cloning:
    #   strength: 0.4
    #   demo_path: "ImitationDemos/MultiSensor_Discrete2"
    #   steps: 2000000
    #   samples_per_update: 2000
    keep_checkpoints: 10
    max_steps: 1000000
    time_horizon: 1000
    summary_freq: 25000
    threaded: false
environment_parameters:
  maze1:
    curriculum:
      - name: "Lesson 0" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 3000
          threshold: 0.9
        value: 0
      # - name: "Lesson 1" # This is the start of the second lesson
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 3000
      #     threshold: 0.85
      #   value: 1
      # - name: "Lesson 2"
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 3000
      #     threshold: 0.8
      #   value: 2
      # - name: "Lesson 3"
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 3000
      #     threshold: 0.8
      #   value: 3
      # - name: "Lesson 4"
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 3000
      #     threshold: 0.75
      #   value: 4
      # - name: "Lesson 5"
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 3000
      #     threshold: 0.75
      #   value: 5
      # - name: "Lesson 6"
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 3000
      #     threshold: 0.75
      #   value: 6
      # - name: "Lesson 7"
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 3000
      #     threshold: 1.1
      #   value: 7
