behaviors:
  Main1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2000
      buffer_size: 20000
      learning_rate: 0.0005
      beta: 0.003
      epsilon: 0.3
      lambd: 0.97
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
      gail:
        strength: 0.2
        gamma: 0.95
        learning_rate: 0.00075
        demo_path: "ImitationDemos/MultiSensor"
      curiosity:
        strength: 0.003
        gamma: 0.95
        network_settings:
          hidden_units: 256
          normalize: true
        learning_rate: 0.00075
    behavioral_cloning:
      strength: 0.4
      demo_path: "ImitationDemos/MultiSensor"
      steps: 10000000
    # memory:
    #   sequence_length: 64
    #   memory_size: 128
    keep_checkpoints: 15
    max_steps: 20000000
    time_horizon: 1000
    summary_freq: 25000
    threaded: false
environment_parameters:
  maze1:
    curriculum:
      - name: "Lesson 0" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 0
      - name: "Lesson 1" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 1
      - name: "Lesson 2"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 750
          threshold: 3
        value: 2
      - name: "Lesson 3"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 3
      - name: "Lesson 4"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 4
      - name: "Lesson 5"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 5
      - name: "Lesson 6"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 3
        value: 6
      # - name: "Lesson 7"
      #   completion_criteria:
      #     measure: reward
      #     behavior: Main1
      #     signal_smoothing: true
      #     min_lesson_length: 500
      #     threshold: 3
      #   value: 7
