behaviors:
  Main1:
    trainer_type: sac
    hyperparameters:
      batch_size: 1048
      buffer_size: 50000
      learning_rate: 1.0e-4
      learning_rate_schedule: constant
      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.8
      reward_signal_steps_per_update: 1.0
      save_replay_buffer: true
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: "ImitationDemos/Main Maze.demo"
      curiosity:
        strength: 0.03
        gamma: 0.99
        network_settings:
          hidden_units: 256
        learning_rate: 1.0e-5
    behavioral_cloning:
        strength: 0.5
        demo_path: "ImitationDemos/Main Maze.demo"
        steps: 250000
        samples_per_update: 0
    max_steps: 10000000
    time_horizon: 480
    summary_freq: 5000
environment_parameters:
  maze1:
    curriculum:
      - name: "Lesson 1" # This is the start of the second lesson
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 7.5
        value: 0
      - name: "Lesson 2"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 7.5
        value: 1
      - name: "Lesson 3"
        completion_criteria:
          measure: reward
          behavior: Main1
          signal_smoothing: true
          min_lesson_length: 20
          threshold: 7.5
        value: 2